spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomm?useSSL=false
    databaseName: ecomm
    serverName: jdbc:mysql://localhost:3306
    database: MYSQL
    username: root
    password: password
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
    sql-script-encoding: utf-8
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/ecomm?useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # Name of the target database to operate on, auto-detected by default.
    database: MYSQL # Target database to operate on
    show_sql: true # Whether to enable logging of SQL statements.
    generate-ddl: false # Whether to initialize the schema on startup.
    hibernate:
      ddl-auto: validate
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR